// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvFD1t8njdHbgjAyqS7nIuqqL6CbqbpU4',
    appId: '1:420452368319:android:c3597f2d6d32cff04aeb0a',
    messagingSenderId: '420452368319',
    projectId: 'distressed-property-70183',
    storageBucket: 'distressed-property-70183.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4MI6kuxmSHcNMuNLMBIPpiYcaUV66dPA',
    appId: '1:420452368319:ios:8734415f2577edf24aeb0a',
    messagingSenderId: '420452368319',
    projectId: 'distressed-property-70183',
    storageBucket: 'distressed-property-70183.appspot.com',
    androidClientId: '420452368319-71p24cahg2cb48cglbp2h64ijhq9n4p0.apps.googleusercontent.com',
    iosClientId: '420452368319-oh3nr0o8posmm1eh6c8g4kpjd8a5qldj.apps.googleusercontent.com',
    iosBundleId: 'com.example.distressedProperty',
  );
}
